import numpy as np
import matplotlib.pyplot as plt
import neuralfoil as nf
import os

# ============================================================
# === FILE READING FUNCTION ==================================
# ============================================================

def read_airfoil_file(filename):
    """Parses the airfoil_points_2412.txt file and extracts control, upper, and lower surfaces."""
    with open(filename, "r") as f:
        lines = f.readlines()

    x_ctrl, y_ctrl, offsets = [], [], []
    xu, yu, xl, yl = [], [], [], []
    section = None

    for line in lines:
        line = line.strip()
        if not line:
            continue
        if "=== Control Points" in line:
            section = "ctrl"
            continue
        elif "=== Upper Surface" in line:
            section = "upper"
            continue
        elif "=== Lower Surface" in line:
            section = "lower"
            continue
        elif "===" in line:
            section = None
            continue

        parts = [p.strip() for p in line.split(",")]
        if section == "ctrl" and len(parts) >= 3:
            x_ctrl.append(float(parts[0]))
            y_ctrl.append(float(parts[1]))
            offsets.append(float(parts[2]))
        elif section == "upper" and len(parts) >= 2:
            xu.append(float(parts[0]))
            yu.append(float(parts[1]))
        elif section == "lower" and len(parts) >= 2:
            xl.append(float(parts[0]))
            yl.append(float(parts[1]))

    return (np.array(x_ctrl), np.array(y_ctrl), np.array(offsets),
            np.array(xu), np.array(yu), np.array(xl), np.array(yl))


# ============================================================
# === NEURALFOIL EVALUATION ==================================
# ============================================================

def prepare_coordinates_for_neuralfoil(xu, yu, xl, yl):
    """Combines upper and lower surfaces into one closed array in Selig format."""
    coords_upper = np.vstack([xu[::-1], yu[::-1]]).T  # reverse upper to start at TE
    coords_lower = np.vstack([xl, yl]).T
    coords = np.vstack([coords_upper, coords_lower[1:]])  # skip duplicate LE point
    return coords


def evaluate_airfoil(coords, alphas, Re=5e5, model_size="xxxlarge", n_crit=9.0, xtr_upper=1.0, xtr_lower=1.0):
    """Evaluates airfoil using NeuralFoil for a given AoA sweep."""
    aero = nf.get_aero_from_coordinates(
        coordinates=coords,
        alpha=alphas,
        Re=Re,
        model_size=model_size,
        n_crit=n_crit,
        xtr_upper=xtr_upper,
        xtr_lower=xtr_lower
    )
    return aero


# ============================================================
# === FILE WRITING (XFOIL-STYLE POLAR OUTPUT) ================
# ============================================================

def save_polar_file(filename, alphas, CL, CD, Cm=None):
    """Saves aerodynamic data to a text file similar to XFOIL polar output."""
    with open(filename, "w") as f:
        f.write("--------------------------------------------------------------\n")
        f.write("  XFOIL-like Polar Output (Generated by NeuralFoil)\n")
        f.write("--------------------------------------------------------------\n")
        f.write("  alpha     CL        CD       Cm        CL/CD\n")
        f.write("--------------------------------------------------------------\n")
        for i in range(len(alphas)):
            alpha = alphas[i]
            cl = CL[i]
            cd = CD[i]
            cl_cd = cl / cd if cd != 0 else np.nan
            cm = Cm[i] if Cm is not None else 0.0
            f.write(f"{alpha:8.3f}  {cl:8.5f}  {cd:8.5f}  {cm:8.5f}  {cl_cd:8.5f}\n")
    print(f"💾 Results saved to '{filename}'")


# ============================================================
# === MAIN PROGRAM ===========================================
# ============================================================

def main():
    filename = "../Morphing/Geometry/airfoil_points_015.txt"
    print(f"📂 Reading airfoil geometry from '{filename}' ...")

    # Read data
    x_ctrl, y_ctrl, offsets, xu, yu, xl, yl = read_airfoil_file(filename)
    print(f"✅ Loaded {len(xu)} upper and {len(xl)} lower surface points.")

    # Prepare airfoil coordinates for NeuralFoil
    coords = prepare_coordinates_for_neuralfoil(xu, yu, xl, yl)

    # Define AoA range and Reynolds number
    alphas = np.linspace(-5, 12, 200)
    Re = 1e6

    # Evaluate aerodynamic performance
    print("🧠 Running NeuralFoil aerodynamic evaluation...")
    aero = evaluate_airfoil(coords, alphas, Re=Re)

    # Extract aerodynamic coefficients safely
    CL = aero.get("CL", aero.get("cl"))
    CD = aero.get("CD", aero.get("cd"))
    Cm = aero.get("CM", aero.get("cm"))

    if CL is None or CD is None:
        raise ValueError("❌ NeuralFoil did not return CL or CD. Check your NeuralFoil version or model size.")

    CL_CD = CL / CD

    # ========================================================
    # === SAVE RESULTS =======================================
    # ========================================================

    # Create simulation results directory if it doesn't exist
    results_dir = "Simulation Results"
    os.makedirs(results_dir, exist_ok=True)

    # Extract the numeric part from the airfoil filename (e.g., 'airfoil_points_000.txt')
    airfoil_number = os.path.splitext(os.path.basename(filename))[0].split('_')[-1]

    # Automatically set polar filename based on airfoil number and Re
    output_file = os.path.join(results_dir, f"polar_NeuralFoil_{airfoil_number}_Re{int(Re):.0f}.txt")
    save_polar_file(output_file, alphas, CL, CD, Cm)

    # ========================================================
    # === PLOTS ==============================================
    # ========================================================

    num_plots = 4 if Cm is not None else 3
    plt.figure(figsize=(10, num_plots * 2.5))

    plt.subplot(num_plots, 1, 1)
    plt.plot(alphas, CL, "b-")
    plt.title("Lift Coefficient (CL) vs Angle of Attack")
    plt.xlabel("Angle of Attack (°)")
    plt.ylabel("CL")
    plt.grid(True)

    plt.subplot(num_plots, 1, 2)
    plt.plot(alphas, CD, "r-")
    plt.title("Drag Coefficient (CD) vs Angle of Attack")
    plt.xlabel("Angle of Attack (°)")
    plt.ylabel("CD")
    plt.grid(True)

    plt.subplot(num_plots, 1, 3)
    plt.plot(alphas, CL_CD, "g-")
    plt.title("Lift-to-Drag Ratio (CL/CD) vs Angle of Attack")
    plt.xlabel("Angle of Attack (°)")
    plt.ylabel("CL/CD")
    plt.grid(True)

    if Cm is not None:
        plt.subplot(num_plots, 1, 4)
        plt.plot(alphas, Cm, "m-")
        plt.title("Pitching Moment Coefficient (Cm) vs Angle of Attack")
        plt.xlabel("Angle of Attack (°)")
        plt.ylabel("Cm")
        plt.grid(True)

    plt.tight_layout()
    plt.show()

    print("✅ Analysis complete. Plots displayed successfully.")


# ============================================================
# === RUN SCRIPT =============================================
# ============================================================

if __name__ == "__main__":
    main()