import numpy as np
import neuralfoil as nf
import os

# ============================================================
# === FILE READING FUNCTION ==================================
# ============================================================

def read_airfoil_file(filename):
    """Parses the airfoil file and extracts control, upper, and lower surfaces."""
    with open(filename, "r") as f:
        lines = f.readlines()

    x_ctrl, y_ctrl, offsets = [], [], []
    xu, yu, xl, yl = [], [], [], []
    section = None

    for line in lines:
        line = line.strip()
        if not line:
            continue
        if "=== Control Points" in line:
            section = "ctrl"
            continue
        elif "=== Upper Surface" in line:
            section = "upper"
            continue
        elif "=== Lower Surface" in line:
            section = "lower"
            continue
        elif "===" in line:
            section = None
            continue

        parts = [p.strip() for p in line.split(",")]
        if section == "ctrl" and len(parts) >= 3:
            x_ctrl.append(float(parts[0]))
            y_ctrl.append(float(parts[1]))
            offsets.append(float(parts[2]))
        elif section == "upper" and len(parts) >= 2:
            xu.append(float(parts[0]))
            yu.append(float(parts[1]))
        elif section == "lower" and len(parts) >= 2:
            xl.append(float(parts[0]))
            yl.append(float(parts[1]))

    return (np.array(x_ctrl), np.array(y_ctrl), np.array(offsets),
            np.array(xu), np.array(yu), np.array(xl), np.array(yl))


# ============================================================
# === NEURALFOIL EVALUATION =================================
# ============================================================

def prepare_coordinates_for_neuralfoil(xu, yu, xl, yl):
    """Combines upper and lower surfaces into one closed array in Selig format."""
    coords_upper = np.vstack([xu[::-1], yu[::-1]]).T  # reverse upper to start at TE
    coords_lower = np.vstack([xl, yl]).T
    coords = np.vstack([coords_upper, coords_lower[1:]])  # skip duplicate LE point
    return coords


def evaluate_airfoil(coords, alphas, Re=5e5, model_size="xxxlarge", n_crit=9.0, xtr_upper=1.0, xtr_lower=1.0):
    """Evaluates airfoil using NeuralFoil for a given AoA sweep."""
    aero = nf.get_aero_from_coordinates(
        coordinates=coords,
        alpha=alphas,
        Re=Re,
        model_size=model_size,
        n_crit=n_crit,
        xtr_upper=xtr_upper,
        xtr_lower=xtr_lower
    )
    return aero


# ============================================================
# === FILE WRITING (XFOIL-STYLE POLAR OUTPUT) ================
# ============================================================

def save_polar_file(filename, alphas, CL, CD, Cm=None):
    """Saves aerodynamic data to a text file similar to XFOIL polar output."""
    with open(filename, "w") as f:
        f.write("--------------------------------------------------------------\n")
        f.write("  XFOIL-like Polar Output (Generated by NeuralFoil)\n")
        f.write("--------------------------------------------------------------\n")
        f.write("  alpha     CL        CD       Cm        CL/CD\n")
        f.write("--------------------------------------------------------------\n")
        for i in range(len(alphas)):
            alpha = alphas[i]
            cl = CL[i]
            cd = CD[i]
            cl_cd = cl / cd if cd != 0 else np.nan
            cm = Cm[i] if Cm is not None else 0.0
            f.write(f"{alpha:8.3f}  {cl:8.5f}  {cd:8.5f}  {cm:8.5f}  {cl_cd:8.5f}\n")
    print(f"💾 Results saved to '{filename}'")


# ============================================================
# === MAIN PROGRAM FOR MULTIPLE AIRFOILS =====================
# ============================================================

def main():
    # Directory to save results
    results_dir = "Simulation Results"
    os.makedirs(results_dir, exist_ok=True)

    # Loop through airfoils 000 to 914 (inclusive)
    for i in range(915):
        num_str = f"{i:03d}"  # zero-padded
        filename = f"../Morphing/Geometry/airfoil_points_{num_str}.txt"

        if not os.path.exists(filename):
            print(f"⚠️ Skipping {filename} — file not found.")
            continue

        print(f"\n📂 Reading airfoil geometry from '{filename}' ...")

        # Read data
        try:
            x_ctrl, y_ctrl, offsets, xu, yu, xl, yl = read_airfoil_file(filename)
        except Exception as e:
            print(f"❌ Error reading {filename}: {e}")
            continue

        print(f"✅ Loaded {len(xu)} upper and {len(xl)} lower surface points.")

        # Prepare airfoil coordinates for NeuralFoil
        coords = prepare_coordinates_for_neuralfoil(xu, yu, xl, yl)

        # Define AoA range and Reynolds number
        alphas = np.linspace(-5, 12, 200)
        Re = 1e6

        # Evaluate aerodynamic performance
        print("🧠 Running NeuralFoil aerodynamic evaluation...")
        try:
            aero = evaluate_airfoil(coords, alphas, Re=Re)
        except Exception as e:
            print(f"❌ NeuralFoil evaluation failed for {num_str}: {e}")
            continue

        # Extract aerodynamic coefficients safely
        CL = aero.get("CL", aero.get("cl"))
        CD = aero.get("CD", aero.get("cd"))
        Cm = aero.get("CM", aero.get("cm"))

        if CL is None or CD is None:
            print(f"❌ NeuralFoil returned no CL/CD for {filename}. Skipping.")
            continue

        # Save results
        output_file = os.path.join(results_dir, f"polar_NeuralFoil_{num_str}_Re{int(Re):.0f}.txt")
        save_polar_file(output_file, alphas, CL, CD, Cm)

        print(f"✅ Airfoil {num_str} processed.\n")

    print("\n🎯 All requested airfoils processed!")


# ============================================================
# === RUN SCRIPT =============================================
# ============================================================

if __name__ == "__main__":
    main()